# Generated by Django 4.1.3 on 2023-03-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='banner',
        ),
    ]
